#! /bin/bash

# github <command> <args>

CMD=$1
shift

if [ $CMD == "init" ]; then
    git init
    git add *
    git commit -m "Initial project"
    git remote add origin git@github.com:$1.git
    git push -u origin master
elif [ $CMD == "clone" ]; then
    git clone git@github.com:$1.git
elif [ $CMD == "ignore" ]; then
    echo "$@" >> .gitignore
fi
