#! /bin/bash

# github <command> <args>

CMD=$1
shift

HEADER_FILE=header.in
AUTHOR=`git config user.name`
YEAR=`date '+%Y'`

if [ $CMD == "help" ]; then
    echo 'GitHub and Git Utilities'
    echo ''
    echo '  init       repo name description'
    echo '  clone      repo'
    echo '  ignore     path_spec'
    echo '  license    files'
elif [ $CMD == "init" ]; then
    cp $UTILS_PATH/resources/COPYING .
    cp $UTILS_PATH/resources/header.in .
    replace '@AUTHOR@' "$AUTHOR" header.in
    replace '@NAME@' "$2" header.in
    replace '@YEAR@' "$YEAR" header.in
    replace '@DESCRIPTION@' "$3" header.in
    git init
    git add *
    git commit -m "Initial project"
    git remote add origin git@github.com:$1.git
    git push -u origin master
elif [ $CMD == "clone" ]; then
    git clone git@github.com:$1.git
elif [ $CMD == "ignore" ]; then
    echo "$@" >> .gitignore
elif [ $CMD == "license" ]; then
    for FILE in $@; do
        cat $HEADER_FILE $FILE > tmpfile && mv tmpfile $FILE
    done
fi
